version: '2'

services:
  mongodb:
    image: mongo:latest
    hostname: mongodb
    ports:
      - "27017:27017"
  arangodb:
    image: arangodb:latest
    hostname: arangodb
    ports:
      - "8529:8529"
    volumes:
      - /tmp/arangodb:/var/lib/arangodb
    environment:
      - ARANGO_NO_AUTH=1
      - ARANGO_ROOT_PASSWORD=password
  neo4j:
    image: neo4j:latest
    hostname: neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - /tmp/neo4j:/data
